# Generated by Django 5.2 on 2025-04-09 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Исходное имя файла, загруженного пользователем', max_length=255, verbose_name='Оригинпльное имя')),
                ('size', models.PositiveIntegerField(help_text='Размер файла в байтах', verbose_name='Размер')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда файл был загружен', verbose_name='Дата загрузки')),
                ('last_download_date', models.DateTimeField(blank=True, help_text='Дата и время последней загрузки файла', null=True, verbose_name='Дата последнего скачивания')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к файлу', null=True, verbose_name='Комментарий')),
                ('file_path', models.FileField(help_text='Путь к файлу на сервере', upload_to='uploads/', verbose_name='Путь к файлу')),
                ('public_link', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальная ссылка для внешнего доступа к файлу', unique=True, verbose_name='Публичная ссылка')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
