# Generated by Django 5.2 on 2025-04-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner'], name='cloud_app_f_owner_i_8718c4_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['-upload_date'], name='cloud_app_f_upload__d1977e_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'original_name'), name='unique_owner_filename'),
        ),
    ]
