# Generated by Django 5.2 on 2025-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='user_<django.db.models.fields.related.ForeignKey>/%Y/%m/%d/'),
        ),
    ]
