# Generated by Django 5.2 on 2025-04-10 17:37

import cloud_app.models
import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к файлу (максимум 500 символов)', max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(help_text='Путь к файлу на сервере', upload_to=cloud_app.models.get_upload_path, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_name',
            field=models.CharField(help_text='Исходное имя файла, загруженного пользователем', max_length=255, verbose_name='Оригинальное имя'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит этот файл', on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(help_text='Размер файла в байтах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Размер'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя папки', max_length=255, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cloud_app.folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Папка, в которой находится файл', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='cloud_app.folder', verbose_name='Папка'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'folder', 'original_name'), name='unique_file_name_per_folder', violation_error_message='Файл с таким именем уже существует в указанной папке'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'parent', 'name')},
        ),
    ]
