# Generated by Django 5.2 on 2025-04-18 05:11

import cloud_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=cloud_app.models.user_directory_path),
        ),
    ]
